### ISSUE TITLE
Make it work with Remix + Vite

### ISSUE THREAD

**Issue by celiacheff** [JinYuSha0/nest-remix#7]
Remix have a new option to use Vite instead of the old build system.
Do you have plans to adapt your code to make it work with Vite please ?
It'll require some changes, since for example the build folder is no more (I  used a vite plugin to copy the client/* files to public/ a each build, working fine).

**Comment by JinYuSha0** [comment]
Yes, I feel that the old build system is getting slower and slower. I have started migrating to vite and have made good progress. It will be coming soon.
