### ISSUE TITLE
Consolidate?

### ISSUE THREAD

**Issue by KerryRitter** [JinYuSha0/nest-remix#8]
Hey team,

Looks like this repo is very similar to my work on `nest-remix` at https://github.com/BeerMoneyDev/nest-remix/

It is always confusing and frustrating for developers to see `nestjs-{something}` and `nest-{something}`.

Is there a way we can consolidate?

Good work expanding on this idea.

**Comment by JinYuSha0** [comment]
Hello, I am very happy to talk to you. Are you willing to join in the cooperation to make this library better? Are you willing to let this library use the npm package name of nest-remix?

**Comment by JinYuSha0** [comment]
Hi, remix has been migrated to react-router v7. I am considering using the package name [nest-react-router](https://www.npmjs.com/package/nest-react-router), so this problem will be solved. If you have good ideas, please continue to communicate with me.
