### ISSUE TITLE
Upgrade Path to React Router 7?

### ISSUE THREAD

**Issue by CraigMcCahill** [JinYuSha0/nest-remix#9]
Hello I've started using your package in an existing project. As you no doubt know Remix will be becoming React-Router 7 at the next version:

https://remix.run/blog/incremental-path-to-react-19

Can I assume you will be updating the package in sync with this change?

**Comment by JinYuSha0** [comment]
Thank you for the reminder. seems support this feature only need to upgrade the remix dependent version. If there were no other difficulties, I would do it. You are also welcome to submit PR.

**Comment by JinYuSha0** [comment]
Migrated to react-route v7, Please see README.md for details
